### ISSUE TITLE
Module not found 'irc'

### ISSUE THREAD

**Issue by abcbarryn** [h1ddenpr0cess20/ollamarama-irc#19]
```
Traceback (most recent call last):
  File "ollamarama.py", line 8, in <module>
    import irc.bot
ModuleNotFoundError: No module named 'irc'
```
```
# pip list | fgrep irc
irc                       20.5.0
irc-bot                   1.0.41
```

What is going on here?

**Comment by abcbarryn** [comment]
Ok I was running python 3.11, I tried 3.6 and not I get:
```
Traceback (most recent call last):
  File "ollamarama.py", line 425, in <module>
    asyncio.run(bot.main())
AttributeError: module 'asyncio' has no attribute 'run'
```

Quote:
The asyncio.run() function was added in Python 3.7. From the [asyncio.run() function documentation](https://docs.python.org/3/library/asyncio-task.html#asyncio.run):

New in version 3.7: Important: this function has been added to asyncio in Python 3.7 on a provisional basis.

In what %$$@$#@#! version of python does this things ACTUALLY work?

**Comment by abcbarryn** [comment]
Finally got it working with python 3.11 and irc==19.0.1

Your requirements.txt file need some TLC.

**Comment by abcbarryn** [comment]
I don't think this issue should be closed. This software failed to run following the build/install instructions posted here on my system without me manually tweaking the versions of the packages from what was installed by requirements.txt and running python 3.11. It might run on python 3.7, 3.8, or 3.9 as it is, but not 3.11 and not 3.6. This will undoubtably impact many other people. At least add a note stating what python versions have been tested and work.

**Comment by h1ddenpr0cess20** [comment]
works just fine in 3.11, and your configuration issues are not my problem.  plus you were rude.

**Comment by abcbarryn** [comment]
It definitely does not work in Python 3.6. Where does it say what Python version is required? My "rudeness" does not invalidate the issue. Plus your closing the issue because of me being frustrated and maybe politically incorrect isn't itself rude? You've never had anyone post a frustrated complaint before??

**Comment by h1ddenpr0cess20** [comment]
never said it did.  please remove my software from your device.  thanks.
